#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_PACKAGE                          144	/*Device.Services.X_ZYXEL_Package.i*/
#define RDM_OID_PACKAGE_INSTALL                  324	/*Device.Services.X_ZYXEL_Package_Install*/
#define RDM_OID_VOICE_SRV                        384	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       468	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1272	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1572	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1632	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1716	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1896	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          2868	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   3000	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4524	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4680	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   4788	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              4968	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              5076	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        5208	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5436	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5688	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  5916	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            6024	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      6108	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6312	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6684	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       6864	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   7236	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7512	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7620	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7728	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    7812	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        7968	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       8100	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9600	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 9756	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            9960	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               10212	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10368	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   11148	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       11760	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     11940	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12312	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12348	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12408	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 12588	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            12672	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 12852	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 12912	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 12996	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        13056	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   13116	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13392	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13452	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   13944	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14268	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_DEV_INFO                         14496	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_FIRMWARE_IMAGE          15132	/*Device.DeviceInfo.FirmwareImage.i*/
#define RDM_OID_DOWNLOAD                         15312	/*Device.DeviceInfo.FirmwareImage.i.Download*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          15516	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_CONFIG_BACKUP                    15672	/*Device.DeviceInfo.VendorConfigFile.i.Backup*/
#define RDM_OID_CONFIG_RESTORE                   15780	/*Device.DeviceInfo.VendorConfigFile.i.Restore*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          15984	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                16116	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 16248	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_LOAD            16332	/*Device.DeviceInfo.ProcessStatus.X_ZYXEL_Load*/
#define RDM_OID_DEV_INFO_PS_STAT_CPU             16512	/*Device.DeviceInfo.ProcessStatus.X_ZYXEL_CPU.i*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              16716	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        16896	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            16956	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     17400	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               17484	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         17568	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_LOG_UPLOAD                       17700	/*Device.DeviceInfo.VendorLogFile.i.Upload*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            17808	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     17940	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_DEV_INFO_POWER_STAT              18096	/*Device.DeviceInfo.X_ZYXEL_PowerStatus*/
#define RDM_OID_APP_SUPPORT_INFO                 18180	/*Device.DeviceInfo.AppSupportInformation*/
#define RDM_OID_MGMT_SRV                         18312	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                20124	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 20304	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                20436	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        20472	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  20580	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          20712	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 20820	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             20952	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             21204	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_GATEWAY_INFO                     21360	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             21468	/*Device.Time*/
#define RDM_OID_USR_INTF                         22128	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              22740	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              22872	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      23100	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              23256	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         23364	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      27360	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                27708	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             28200	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        28692	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         28776	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         29268	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             29352	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      29916	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   30432	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             30780	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          30960	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     31140	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           31320	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           31500	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      31680	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       32196	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   32280	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 32316	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   32544	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             33012	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       33312	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            33612	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  33912	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               33948	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         34368	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          34404	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              35304	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         35364	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      35712	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              35940	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         36000	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      36540	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     37032	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         37188	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   37224	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   37524	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              37824	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         37884	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      38448	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              38844	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      38976	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        39540	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      40008	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         40404	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      40728	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    41124	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 41424	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              41820	/*Device.USB*/
#define RDM_OID_USB_INTF                         41904	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    42204	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         42600	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     42828	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                42888	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            43116	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        43632	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        43788	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   43872	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_BT                               44004	/*Device.Bluetooth*/
#define RDM_OID_BT_INTF                          44088	/*Device.Bluetooth.X_ZYXEL_Interface.i*/
#define RDM_OID_CELL                             44244	/*Device.Cellular*/
#define RDM_OID_CELL_INTF                        44520	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELL_INTF_USIM                   45876	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELL_INTF_ST                     46320	/*Device.Cellular.Interface.i.Stats*/
#define RDM_OID_CELL_INTF_ZY_BUDGET_CONTROL      46716	/*Device.Cellular.Interface.i.X_ZYXEL_BudgetControl*/
#define RDM_OID_CELL_INTF_ZY_IP_PASS_THRU        47376	/*Device.Cellular.Interface.i.X_ZYXEL_IP_PassThrough*/
#define RDM_OID_CELL_INTF_ZY_UI_WAIT_ST          47604	/*Device.Cellular.Interface.i.X_ZYXEL_UiWaitingState*/
#define RDM_OID_CELL_INTF_ZY_SCC                 47784	/*Device.Cellular.Interface.i.X_ZYXEL_SecondaryComponentCarrier.i*/
#define RDM_OID_CELL_INTF_ZY_PCI_LOCK            48156	/*Device.Cellular.Interface.i.X_ZYXEL_PhyCellIdLock*/
#define RDM_OID_CELL_INTF_ZY_PCI_LOCKED_LIST     48264	/*Device.Cellular.Interface.i.X_ZYXEL_PhyCellIdLock.PhyCellIdLockedList.i*/
#define RDM_OID_CELL_INTF_ZY_QSCAN               48348	/*Device.Cellular.Interface.i.X_ZYXEL_QSCAN*/
#define RDM_OID_CELL_INTF_ZY_QSCAN_LIST          48456	/*Device.Cellular.Interface.i.X_ZYXEL_QSCAN.QscanList.i*/
#define RDM_OID_CELL_INTF_ZY_PCI_LOCK_NR         48684	/*Device.Cellular.Interface.i.X_ZYXEL_PhyCellIdLock_NR*/
#define RDM_OID_CELL_INTF_ZY_NBR_CELL            48864	/*Device.Cellular.Interface.i.X_ZYXEL_NeighbourCell.i*/
#define RDM_OID_CELL_INTF_ZY_NR_NSA              49116	/*Device.Cellular.Interface.i.X_ZYXEL_NewRadioNonStandAlone*/
#define RDM_OID_CELL_INTF_ZY_SMS                 49416	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService*/
#define RDM_OID_CELL_INTF_ZY_SMS_INBOX           49548	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService.Inbox.i*/
#define RDM_OID_CELL_INTF_ZY_SMS_OUTBOX          49728	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService.Outbox.i*/
#define RDM_OID_CELL_INTF_ZY_SMS_STORAGE         49908	/*Device.Cellular.Interface.i.X_ZYXEL_ShortMessageService.Storage*/
#define RDM_OID_CELL_ACCESS_POINT                50016	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_CELL_ZY_GNSS_LOC                 50460	/*Device.Cellular.X_ZYXEL_GNSS_Location*/
#define RDM_OID_CELL_INTF_ZY_RESET_CM            50808	/*Device.Cellular.X_ZYXEL_Reset_CM*/
#define RDM_OID_CELL_ZY_NBR                      50868	/*Device.Cellular.X_ZYXEL_NBR*/
#define RDM_OID_HPNA                             50928	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        50988	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     51672	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    52068	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          52128	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              52500	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        52728	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         52764	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  53040	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              53244	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     53352	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 53460	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  54096	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 54180	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             54480	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        54540	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     55440	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    55836	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            55944	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              56124	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              56568	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         56628	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      57192	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               57588	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        57744	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    57804	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 58224	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          58740	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              58944	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         59004	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      59544	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               59940	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            60240	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              60396	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         60504	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        60540	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             60720	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    60900	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       60960	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    62676	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        62928	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   63588	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                63984	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            64356	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     65376	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            65604	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      66048	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   66324	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  66576	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   66660	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                66840	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               66972	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           67032	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       67212	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WPS                              67344	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  67452	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          67560	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 68004	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   68448	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_BRIDGING                         68772	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      69048	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 69348	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              69816	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 70212	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             70344	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  70500	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              71328	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        71412	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  72360	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  72396	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   72528	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  72684	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   72768	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               73164	/*Device.IP*/
#define RDM_OID_IP_IFACE                         73416	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 74916	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 75168	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               75540	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    75984	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   76380	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          76536	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   76644	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 77136	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          77508	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  77640	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_PER_CONNECTION_RESULT            78396	/*Device.IP.Diagnostics.DownloadDiagnostics.PerConnectionResult.i*/
#define RDM_OID_INCREMENTAL_RESULT               78624	/*Device.IP.Diagnostics.DownloadDiagnostics.IncrementalResult.i*/
#define RDM_OID_IP_DIAG_UL_DIAG                  78780	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             79200	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            79524	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         80040	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_IP_LAYER_CAP_METRICS     80268	/*Device.IP.Diagnostics.IPLayerCapacityMetrics*/
#define RDM_OID_IP_DIAG_IP_LAYER_MODAL           82080	/*Device.IP.Diagnostics.IPLayerCapacityMetrics.ModalResult.i*/
#define RDM_OID_IP_DIAG_IP_LAYER_INCRE_RES       82404	/*Device.IP.Diagnostics.IPLayerCapacityMetrics.IncrementalResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          82656	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IP_DIAG_NUT_TCP_DIAG             82980	/*Device.IP.Diagnostics.X_ZYXEL_NUTTCP*/
#define RDM_OID_I_P_CONN_TRACK                   83376	/*Device.IP.X_ZYXEL_IP_CONNTRACK*/
#define RDM_OID_IPSEC                            83484	/*Device.IPSec*/
#define RDM_OID_IPSEC_STAT                       83856	/*Device.IPSec.Stats*/
#define RDM_OID_IPSEC_FILTER                     84180	/*Device.IPSec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    84744	/*Device.IPSec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       85380	/*Device.IPSec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     85512	/*Device.IPSec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                85644	/*Device.IPSec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    85800	/*Device.IPSec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               86148	/*Device.IPSec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   86376	/*Device.IPSec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           86460	/*Device.IPSec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      86616	/*Device.IPSec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_GRE                              86892	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       86976	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  87612	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 87888	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            88188	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       88416	/*Device.GRE.Filter.i*/
#define RDM_OID_CAPT_PORTAL                      88668	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          88800	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   88860	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            89088	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            89604	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      89880	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             89988	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  90240	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         90324	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               90600	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      90684	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           90984	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  91068	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              91656	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           91788	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      91872	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          92172	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 92256	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              92604	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          93216	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          95340	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         95616	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      95940	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          96504	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     97044	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       97344	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     97524	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            97584	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       97668	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               98592	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               98652	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                98712	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              99012	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       99168	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   99276	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        99552	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    99660	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         99840	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          99876	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   100128	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              100308	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 100584	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 100740	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              101256	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 101580	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  101904	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           102084	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    102144	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  102612	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   102744	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       102900	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  103008	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      103860	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              103992	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           104124	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   104280	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       104364	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                104448	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_SRV_CUS_DHCP_OPT          104628	/*Device.DHCPv4.Server.X_ZYXEL_Custom_DHCP_Option.i*/
#define RDM_OID_DHCPV4_RELAY                     104736	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 104844	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           105288	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    105348	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                105792	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           105900	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       106032	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       106140	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  106224	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           107076	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   107256	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 107364	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       107472	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              107556	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV6_RELAY                     107712	/*Device.DHCPv6.Relay*/
#define RDM_OID_DHCPV6_RELAY_INTF_SET            107844	/*Device.DHCPv6.Relay.InterfaceSetting.i*/
#define RDM_OID_IEEE8021X                        108072	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             108132	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        108600	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      108900	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      108984	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             109068	/*Device.Users*/
#define RDM_OID_USRS_USR                         109128	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               109308	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           109368	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        109596	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             109752	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         109788	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    110112	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        110436	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               110544	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    110748	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                110952	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             111132	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        111312	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   111540	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         111624	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   111948	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   112200	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              112356	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  113400	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       113508	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 113856	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        114156	/*Device.SoftwareModules*/
#define RDM_OID_INSTALL_D_U                      114264	/*Device.SoftwareModules.InstallDU*/
#define RDM_OID_S_W_MOD_D_U_STATE_CHANGE         114420	/*Device.SoftwareModules.DUStateChange*/
#define RDM_OID_SW_MODULE_EXEC_ENV               114672	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        115164	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_S_W_MOD_UPDATE                   115536	/*Device.SoftwareModules.DeploymentUnit.i.Update*/
#define RDM_OID_S_W_MOD_UNINSTALL                115644	/*Device.SoftwareModules.DeploymentUnit.i.Uninstall*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              115680	/*Device.SoftwareModules.ExecutionUnit.i*/
#define RDM_OID_S_W_MOD_E_U_SET_REQUESTED_STATE  116220	/*Device.SoftwareModules.ExecutionUnit.i.SetRequestedState*/
#define RDM_OID_FAULT_MGMT                       116280	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            116460	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         116616	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         116892	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       117168	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            117444	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          117720	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     117780	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              118248	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          118284	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         118656	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            119028	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    119256	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               119316	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    119520	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               119676	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               120024	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   120108	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           120336	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           120540	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      120744	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               120972	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   121104	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           121284	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           121464	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      121644	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        121824	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   122076	/*Device.BulkData.Profile.i*/
#define RDM_OID_C_S_V_ENCODING                   122520	/*Device.BulkData.Profile.i.CSVEncoding*/
#define RDM_OID_J_S_O_N_ENCODING                 122676	/*Device.BulkData.Profile.i.JSONEncoding*/
#define RDM_OID_BULK_DATA_PROFILE_H_T_T_P        122760	/*Device.BulkData.Profile.i.HTTP*/
#define RDM_OID_BULK_DATA_PROF_PARAM_PUSH        123108	/*Device.BulkData.Profile.i.Push*/
#define RDM_OID_BULK_DATA_PROF_PARAM             123168	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_LOCAL_AGENT                      123252	/*Device.LocalAgent*/
#define RDM_OID_DEV_INFO_LOCAL_AGENT_TRANSFER_COMPLETE 123744	/*Device.LocalAgent.TransferComplete*/
#define RDM_OID_DEV_LOCAL_AGENT_SUB_TOPIC_LIST   124020	/*Device.LocalAgent.X_ZYXEL_Subscription_Topic_List.i*/
#define RDM_OID_DEV_LOCAL_AGENT_M_T_P            124128	/*Device.LocalAgent.MTP.i*/
#define RDM_OID_DEV_LOCAL_AGENT_M_T_P_CO_A_P     124284	/*Device.LocalAgent.MTP.i.CoAP*/
#define RDM_OID_DEV_LOCAL_AGENT_M_T_P_S_T_O_M_P  124440	/*Device.LocalAgent.MTP.i.STOMP*/
#define RDM_OID_DEV_LOCAL_AGENT_M_T_P_WEB_SOCKET 124548	/*Device.LocalAgent.MTP.i.WebSocket*/
#define RDM_OID_DEV_LOCAL_AGENT_M_T_P_M_Q_T_T    124680	/*Device.LocalAgent.MTP.i.MQTT*/
#define RDM_OID_DEV_LOCAL_AGENT_SUBSCRIPTION     124812	/*Device.LocalAgent.Subscription.i*/
#define RDM_OID_DEV_LOCAL_AGENT_REQUEST          125112	/*Device.LocalAgent.Request.i*/
#define RDM_OID_CANCEL                           125268	/*Device.LocalAgent.Request.i.Cancel*/
#define RDM_OID_DEV_LOCAL_AGENT_CERTIFICATE      125304	/*Device.LocalAgent.Certificate.i*/
#define RDM_OID_DELETE                           125460	/*Device.LocalAgent.Certificate.i.Delete*/
#define RDM_OID_DEV_LOCAL_AGENT_CERT_ROLE_MAPPING_LIST 125496	/*Device.LocalAgent.X_ZYXEL_CertRoleMappingList.i*/
#define RDM_OID_DEV_LOCAL_AGENT_CONTROLLER_TRUST 125604	/*Device.LocalAgent.ControllerTrust*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TRUST_REQ_CHALLENGE 125808	/*Device.LocalAgent.ControllerTrust.RequestChallenge*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TRUST_CHALLENGE_RESP 125988	/*Device.LocalAgent.ControllerTrust.ChallengeResponse*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TRUST_ROLE 126072	/*Device.LocalAgent.ControllerTrust.Role.i*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TRUST_ROLE_PERMISSION 126204	/*Device.LocalAgent.ControllerTrust.Role.i.Permission.i*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TRUST_CREDENTIAL 126432	/*Device.LocalAgent.ControllerTrust.Credential.i*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TRUST_CHALLENGE 126588	/*Device.LocalAgent.ControllerTrust.Challenge.i*/
#define RDM_OID_DEV_LOCAL_AGENT_CONTROLLER       126888	/*Device.LocalAgent.Controller.i*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_SCHEDULE_TIMER 127284	/*Device.LocalAgent.Controller.i.ScheduleTimer*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TIMER     127344	/*Device.LocalAgent.Controller.i.Timer*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_ADD_MY_CERTIFICATE 127404	/*Device.LocalAgent.Controller.i.AddMyCertificate*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_SEND_ON_BOARD_REQUEST 127488	/*Device.LocalAgent.Controller.i.SendOnBoardRequest*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_M_T_P     127524	/*Device.LocalAgent.Controller.i.MTP.i*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_M_T_P_CO_A_P 127632	/*Device.LocalAgent.Controller.i.MTP.i.CoAP*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_M_T_P_S_T_O_M_P 127764	/*Device.LocalAgent.Controller.i.MTP.i.STOMP*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_M_T_P_WEB_SOCKET 127848	/*Device.LocalAgent.Controller.i.MTP.i.WebSocket*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_M_T_P_WEB_SOCKET_RESET 128100	/*Device.LocalAgent.Controller.i.MTP.i.WebSocket.Reset*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_M_T_P_M_Q_T_T 128136	/*Device.LocalAgent.Controller.i.MTP.i.MQTT*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_TRANSFER_COMPLETE_POLICY 128268	/*Device.LocalAgent.Controller.i.TransferCompletePolicy*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_BOOT_PARAMETER 128328	/*Device.LocalAgent.Controller.i.BootParameter.i*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_E2_E_SESSION 128436	/*Device.LocalAgent.Controller.i.E2ESession*/
#define RDM_OID_LOCAL_AGENT_CONTROLLER_E2_E_SESSION_RESET 128688	/*Device.LocalAgent.Controller.i.E2ESession.Reset*/
#define RDM_OID_ADD_CERTIFICATE                  128724	/*Device.LocalAgent.AddCertificate*/
#define RDM_OID_MQTT                             128808	/*Device.MQTT*/
#define RDM_OID_MQTT_CAPABILITY                  128892	/*Device.MQTT.Capability*/
#define RDM_OID_MQTT_CLIENT                      128976	/*Device.MQTT.Client.i*/
#define RDM_OID_MQTT_CLIENT_PUB_CONF             130020	/*Device.MQTT.Client.i.X_ZYXEL_Publish_Config.i*/
#define RDM_OID_MQTT_CLIENT_STATS                130152	/*Device.MQTT.Client.i.Stats*/
#define RDM_OID_ROM_CONVERT                      130404	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         130464	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     130740	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     130776	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   131004	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        131184	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   131244	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       131520	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       132012	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           132264	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     132396	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        132624	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            132708	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        133128	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       133356	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      133464	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_ZY_HOST_NAME_REPLACE             133596	/*Device.X_ZYXEL_EXT.HostNameReplace*/
#define RDM_OID_PPTP_CFG                         133656	/*Device.X_ZYXEL_EXT.X_ZYXEL_PPTP_Config*/
#define RDM_OID_EOGRE_CFG                        133956	/*Device.X_ZYXEL_EXT.X_ZYXEL_EoGRE_Config*/
#define RDM_OID_LAN_DEV                          134136	/*Device.X_ZYXEL_EXT.LANDevice.i*/
#define RDM_OID_ZY_IGMP                          134244	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          134736	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        134892	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           135000	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       135420	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    135528	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            135684	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    136440	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         136548	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            136656	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     136764	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     136920	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     137004	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   137088	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   137220	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   137304	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             137388	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        137448	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         137532	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            137832	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      137940	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         138216	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           138348	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  138456	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_REMO_MGMT_IP_PASS_THRU           138588	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough*/
#define RDM_OID_REMO_SRV_IP_PASS_THRU            138672	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN_IP_PASS_THRU 138948	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV_IP_PASS_THRU         139056	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN_IP_PASS_THRU 139332	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN_IP_PASS_THRU 139464	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN_IP_PASS_THRU     139572	/*Device.X_ZYXEL_RemoteManagement_IP_PassThrough.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      139704	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   139764	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      140016	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_GPON_INFO                        140244	/*Device.X_ZYXEL_GPON_Info*/
#define RDM_OID_LOG_SETTING                      140448	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     140700	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     140808	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 140988	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      141120	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       141252	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 141432	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 141588	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            141648	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                141708	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            142152	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        142308	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  142992	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_SAMBA                         143220	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     143304	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                143556	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 143952	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     144132	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     144456	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               144516	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       144648	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             144780	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              144816	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              145524	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              145992	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       146124	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         146232	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        146340	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               146472	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           146628	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             146712	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          146868	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           146952	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         147036	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             147072	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          147276	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            147432	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            147516	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           147672	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        147852	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         147912	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              148140	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         148200	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      148332	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            148392	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      148452	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   148512	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 148620	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 148704	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          148836	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             148944	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               149220	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_ONLINE_MODULE_UPGRADE            149520	/*Device.X_ZYXEL_Online_Module_Upgrade*/
#define RDM_OID_LANDING_PAGE                     149796	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       149880	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   150276	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    150432	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              150540	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_RESET_ADMIN                   150600	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_OI_WIZARD                        150660	/*Device.X_ZYXEL_OiWizard*/
#define RDM_OID_ZY_DATA_USAGE                    150864	/*Device.X_ZYXEL_DataUsage*/
#define RDM_OID_ZY_DATA_USAGE_LAN                150924	/*Device.X_ZYXEL_DataUsage.Lan.i*/
#define RDM_OID_ZY_DATA_USAGE_WAN                151032	/*Device.X_ZYXEL_DataUsage.Wan.i*/
#define RDM_OID_XMPP                             151140	/*Device.XMPP*/
#define RDM_OID_XMPP_CONN                        151224	/*Device.XMPP.Connection.i*/
#define RDM_OID_XMPP_CONN_SRV                    151692	/*Device.XMPP.Connection.i.Server.i*/
#define RDM_OID_IPERF                            151872	/*Device.X_TELECOMITALIA_IT_Iperf*/
#define RDM_OID_L2_T_PV3                         152004	/*Device.X_ZYXEL_L2TPv3.i*/

#define RDM_OID_MAX                   152304     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
